'use strict';

import * as jsPDF from 'jspdf';

const A4_SIZE = {width: 210, height: 297};

export default function generate() {
    let logo = document.getElementsByTagName("img")[0];
    let field = document.getElementById("field-canvas");
    let qr_code_top_left = document.getElementById("qr-code_top_left");
    let qr_code_top_right = document.getElementById("qr-code_top_right");
    let qr_code_bottom_left = document.getElementById("qr-code_bottom_left");
    let qr_code_bottom_right = document.getElementById("qr-code_bottom_right");

    let encoded_string = document.getElementById("encoded-field");
    let element_coords = document.getElementById("field-descr");

    let doc = new jsPDF({ unit: 'mm', format: "a4" });

    let shift = 0;
    for (let coords of element_coords.children) {
        doc.text(coords.innerText, 120, 25 + shift);
        shift += 10;
    }

    doc.addImage(logo, 'PNG', 15, 5, 55, 10);
    doc.addImage(field, 'PNG', 15, 25, 100, 100);
    doc.addHTML($('qr-codes'), 15, 150);
    doc.text(encoded_string.innerText, 15, 140);

    doc.text("Generated by " + window.location.href, 15, A4_SIZE.height - 10);

    doc.save('a4.pdf');
}
