'use strict';

import * as jsPDF from 'jspdf';

const A4_SIZE = {width: 210, height: 297};

export default function generate() {
    let logo = document.getElementsByTagName("img")[0];
    let field = document.getElementById("field-canvas");
    let qr_codes = document.getElementById('qr-codes');
    let qr_code_top_right = document.getElementById("qr-code-top-right");
    let qr_code_top_left = document.getElementById("qr-code-top-left");
    let qr_code_bottom_left = document.getElementById("qr-code-bottom-left");
    let qr_code_bottom_right = document.getElementById("qr-code-bottom-right");

    let true_encoded_string = document.getElementById("true-encoded-field");
    let encoded_string_top_right = document.getElementById("encoded-field-top-right");
    let encoded_string_top_left = document.getElementById("encoded-field-top-left");
    let encoded_string_bottom_left = document.getElementById("encoded-field-bottom-left");
    let encoded_string_bottom_right = document.getElementById("encoded-field-bottom-right");
    
    let element_coords = document.getElementById("field-descr");

    let doc = new jsPDF({ unit: 'mm', format: "a4" });

    let shift = 0;
    for (let coords of element_coords.children) {
        doc.text(coords.innerText, 110, 15 + shift);
        shift += 10;
    }

    doc.addImage(logo, 'PNG', 5, 0, 55, 10);
    doc.addImage(field, 'PNG', 5, 15, 100, 100);
    doc.setFontSize(11);
    doc.text(true_encoded_string.innerText, 110, 80);
    doc.text(encoded_string_top_right.innerText, 110, 85);
    doc.text(encoded_string_top_left.innerText, 110, 90);
    doc.text(encoded_string_bottom_left.innerText, 110, 95);
    doc.text(encoded_string_bottom_right.innerText, 110, 100);
    

    doc.rect(15,120,165,270);
    doc.addImage(qr_code_top_left, 'PNG', 22.5, 127.5, 60, 60);
    doc.addImage(qr_code_top_right, 'PNG', 97.5, 127.5, 60, 60);
    doc.addImage(qr_code_bottom_left, 'PNG', 22.5, 202.5, 60, 60);
    doc.addImage(qr_code_bottom_right, 'PNG', 97.5, 202.5, 60, 60);

    
    doc.text("Generated by " + window.location.href, 15, A4_SIZE.height - 10);

    doc.save('a4.pdf');
}
